In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
arr1, arr2

(array([1, 2, 3, 4]), array([10, 20, 30, 40]))

In [4]:
np.concatenate((arr1, arr2))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [8]:
arr3 = np.arange(1, 10).reshape((3,3))
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr4 = np.arange(2, 11).reshape(3,3)
arr4

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
np.concatenate((arr3,arr4), axis=1)  #axis for rowwise or columnwise : 1 is column, 0 is row

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])

In [12]:
np.concatenate((arr3,arr4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
np.vstack((arr3,arr4))  #vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [17]:
np.hstack((arr3, arr4))  #horizontally

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])

In [28]:
np.split(arr3, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [21]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.split(arr3,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]