In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1, 18, 2).reshape(3,3)
arr1

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [3]:
arr2 = np.arange(2, 19, 2).reshape(3,3)
arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### add

In [4]:
arr1 + arr2 

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [5]:
np.add(arr1, arr2)

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [6]:
arr1[0][2]

5

### subtract

In [7]:
arr2 - arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
arr1, arr2

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

In [9]:
np.subtract(arr2, arr1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### multiply

In [10]:
arr1 * arr2

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [11]:
np.multiply(arr1, arr2)

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

### divide

In [12]:
np.divide(arr2, arr1)

array([[2.        , 1.33333333, 1.2       ],
       [1.14285714, 1.11111111, 1.09090909],
       [1.07692308, 1.06666667, 1.05882353]])

In [13]:
arr2 / arr1

array([[2.        , 1.33333333, 1.2       ],
       [1.14285714, 1.11111111, 1.09090909],
       [1.07692308, 1.06666667, 1.05882353]])

In [14]:
#dot, max, argmax, min, argmin, sum, mean, sqrt, exp, std, log, log10

In [15]:
arr1, arr2

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

### dot

In [22]:
np.dot(arr1, arr2)  #arr1@arr2

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [23]:
np.max(arr1)

17

In [25]:
np.argmax(arr1)

8

In [26]:
np.min(arr1)

1

In [27]:
np.argmin(arr1)

0

In [28]:
np.sum(arr1)

81

In [30]:
np.mean(arr1)

9.0

In [31]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [32]:
np.exp(arr1)  #e**1, e**2, e**3

array([[2.71828183e+00, 2.00855369e+01, 1.48413159e+02],
       [1.09663316e+03, 8.10308393e+03, 5.98741417e+04],
       [4.42413392e+05, 3.26901737e+06, 2.41549528e+07]])

In [33]:
np.std(arr1)

5.163977794943222

In [34]:
np.log(arr1)

array([[0.        , 1.09861229, 1.60943791],
       [1.94591015, 2.19722458, 2.39789527],
       [2.56494936, 2.7080502 , 2.83321334]])

In [35]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.69897   ],
       [0.84509804, 0.95424251, 1.04139269],
       [1.11394335, 1.17609126, 1.23044892]])