In [1]:
import numpy as np

### arange
1. Same like range
2. Only return array where range return object
3. np.arange(start, stop, step)

In [2]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape

In [3]:
arr2 = arr.reshape(3, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [5]:
arr3 = np.linspace(1, 10, 6)
arr3

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [6]:
arr4 = np.linspace(1, 2, 100)
arr4

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [7]:
arr3 = np.arange(1, 25).reshape(2,4,3) #2 * 4 * 3 = 24
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### ravel

In [9]:
arr4 = arr2.ravel()
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr5 = arr3.ravel()
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [12]:
arr3.ndim

3

In [13]:
arr5.ndim

1

### flatten

In [14]:
arr6 = arr3.flatten('C')
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
arr6 = arr3.flatten('F')  #Fortran style
arr6

array([ 1, 13,  4, 16,  7, 19, 10, 22,  2, 14,  5, 17,  8, 20, 11, 23,  3,
       15,  6, 18,  9, 21, 12, 24])

### transpose

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr7 = arr2.transpose()
arr7

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
arr3    #2, 4, 3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [19]:
arr3.transpose()  #3, 4, 2

array([[[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]],

       [[ 3, 15],
        [ 6, 18],
        [ 9, 21],
        [12, 24]]])

### Broadcasting
The array which have only one element is broaded equal to another array's length of elements

In [20]:
arr = np.array([10, 20, 30, 40])
arr2 = np.array([10])
arr + arr2

array([20, 30, 40, 50])