In [1]:
import numpy as np

In [59]:
np.random.random()  #return random float value

0.48094256674830993

In [70]:
np.random.randint(1,10,(5,3,4))

array([[[8, 3, 8, 1],
        [9, 7, 8, 9],
        [1, 7, 7, 5]],

       [[1, 5, 7, 1],
        [6, 4, 8, 2],
        [3, 5, 7, 4]],

       [[6, 6, 5, 2],
        [3, 3, 8, 4],
        [2, 8, 3, 1]],

       [[5, 9, 4, 9],
        [6, 9, 8, 4],
        [8, 9, 3, 8]],

       [[9, 2, 8, 3],
        [2, 4, 2, 3],
        [2, 9, 1, 9]]])

In [73]:
np.random.rand(3, 4)  #0, 1

array([[0.42295775, 0.43735485, 0.89788432, 0.63522366],
       [0.10539425, 0.98593139, 0.96104241, 0.58272602],
       [0.27286585, 0.49559486, 0.70635188, 0.81563184]])

In [74]:
np.random.randn(10)  #Bell curve

array([ 1.83266468,  0.38964625,  0.28766943,  0.17430935, -0.91607415,
       -0.87003561,  0.3980957 , -0.66167244, -0.05741132, -0.66208855])

In [99]:
np.random.choice([1,2,3,4,5,6], 2)

array([4, 3])

In [109]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.random.permutation(arr)

array([4, 5, 2, 3, 6, 1])