In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 50, 2).reshape(5,5)
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [4]:
arr[2]

array([21, 23, 25, 27, 29])

In [5]:
arr[2][1]

23

In [6]:
arr[2][3]

27

In [7]:
arr[2][3] = 30

In [8]:
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 30, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [10]:
arr[1:3]

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 30, 29]])

In [11]:
arr[1:3, 2:4]

array([[15, 17],
       [25, 30]])

In [12]:
arr[2:]

array([[21, 23, 25, 30, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [13]:
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 30, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [14]:
arr[:]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 30, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [15]:
arr[:,:]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 30, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [16]:
arr[1:4,2:4]

array([[15, 17],
       [25, 30],
       [35, 37]])

In [19]:
arr[[0, 1, 3]]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [31, 33, 35, 37, 39]])

In [22]:
arr[[0, 1, 3]]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [31, 33, 35, 37, 39]])

In [23]:
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 30, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [24]:
arr[:,[1,3]]

array([[ 3,  7],
       [13, 17],
       [23, 30],
       [33, 37],
       [43, 47]])